/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cursoemvideo.telagenio;

/**
 *
 * @author Apple
 */
public class TelaGenio extends javax.swing.JFrame
{

    /**
     * Creates new form TelaGenio
     */
    public TelaGenio()
    {
        initComponents();
        textFrase.setText("<html>Estou pensando em alguns numeros entre 0 e 10.</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spinnerEscolhaNumero = new javax.swing.JSpinner();
        textFrase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonPalpite = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(650, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cursoemvideo/telagenio/genio.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("28 Days Later", 1, 14)); // NOI18N
        jLabel3.setText("Qual valor estou pensando ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        spinnerEscolhaNumero.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(spinnerEscolhaNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 70, -1));

        textFrase.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        textFrase.setText("Frase");
        textFrase.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(textFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/cursoemvideo/telagenio/balao.png"))); // NOI18N
        jLabel1.setText(" ");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel1.setDisabledIcon(null);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 182));
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        buttonPalpite.setText("Palpite");
        buttonPalpite.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("28 Days Later", 1, 14)); // NOI18N
        jLabel5.setText("de 0 a 10?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("28 Days Later", 1, 14)); // NOI18N
        jLabel6.setText("Qual ? ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPalpiteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonPalpiteActionPerformed
    {//GEN-HEADEREND:event_buttonPalpiteActionPerformed
        // TODO add your handling code here:
       double m  = 1 + Math.random() * (11 -1);
       int valor = (int) m;
       
       int num = Integer.parseInt(spinnerEscolhaNumero.getValue().toString());
       
       String ac = "<html>ACERTOU, PARABENS!</html>";
       String er = "<html>Xiiii, ERROU Gafanhoto, eu pensei em " + valor + "</html>";
       
       String resposta = (valor == num)?ac:er;
       
       textFrase.setText(resposta);
       
       
       
       
       
       
    }//GEN-LAST:event_buttonPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner spinnerEscolhaNumero;
    private javax.swing.JLabel textFrase;
    // End of variables declaration//GEN-END:variables
}
